parser: babel-eslint

extends: "eslint:recommended"

ecmaFeatures:
  modules: true

env:
  browser: true
  node: true
  commonjs: true
  es6: true

rules:
  comma-dangle: 1
  no-console: 0
  no-unused-vars: 1
  no-unexpected-multiline: 2
  valid-jsdoc:
    - 1
    - requireReturnDescription: false
  eqeqeq: 1
  no-caller: 1
  no-case-declarations: 1
  no-empty-pattern: 2
  no-eq-null: 1
  no-extend-native: 1
  no-extra-bind: 1
  no-floating-decimal: 1
  no-implicit-coercion: 1
  no-loop-func: 2
  no-native-reassign: 2
  no-new-wrappers: 1
  no-new: 2
  no-param-reassign: 1
  no-return-assign: 1
  no-self-compare: 1
  no-unused-expressions:
    - 1
    - allowShortCircuit: true
  radix: 1
  no-catch-shadow: 1
  no-shadow-restricted-names: 1
  no-use-before-define:
    - 1
    - nofunc
  require-yield: 2
  no-this-before-super: 2
  constructor-super: 2
  no-const-assign: 2
  no-dupe-class-members: 1
  no-var: 1
  prefer-const: 1

globals:
  module: false
