# Site settings
title: The Making of History
legal: All Rights Reserved
# email: enquiries@leeds-ebooks.co.uk
description: >
  History at its worst. # Pure, unfiltered history. # Untapped history. #
  History best not repeated. # History written by the victors, mocked by us.
baseurl: /making-of-history # the subpath of your site, e.g. /blog/
url: http://leeds-ebooks.github.io # the base hostname & protocol for your site
# twitter_username: BenStyles
# github_username:  leeds-ebooks

exclude: ['src', '.jshintrc', 'package.json', 'node_modules', '.gitignore']

permalink: /article/:title/

# Assets
sass:
  style: compressed

prose:
  rooturl: ""
  siteurl: "http://leeds-ebooks.github.io/making-of-history"
  media: "images"
  ignore:
    - '_includes'
    - '_layouts'
    - '_sass'
    - 'css'
    - 'js'
    - 'src'
    - 'timeline'
    - '_config.yml'
    - '.eslint.yml'
    - '.gitignore'
    - 'feed.xml'
    - 'index.html'
    - 'package.json'
    - 'webpack.config.js'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "article title"
          type: "text"
      - name: "featuredimage"
        field:
          element: "text"
          label: "featured image url"
          help: 'Paste here the url from the body of the article, without "{{site.baseurl}}" e.g. "/images/lovely-picture.jpg"'
          placeholder: "url/to/the/image.jpg"
          type: "text"
      - name: "period"
        field:
          element: "text"
          label: "year (4 digits required!) or range (separated by single hyphen, no spaces)"
          help: 'e.g. 1735 or 1730-1736'
          type: "text"
      - name: "location"
        field:
          element: "text"
          label: "city or country"
          type: "text"
