# Site settings
title: Making of History
email: enquiries@leeds-ebooks.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Affordable handmade digital products for writers, artists and creators.
baseurl: "/making-of-history" # the subpath of your site, e.g. /blog/
# url: "http://leeds-ebooks.co.uk" # the base hostname & protocol for your site
twitter_username: BenStyles
github_username:  leeds-ebooks

permalink: /blog/:year/:month/:title/

# Assets
sass:
  style: compressed

prose:
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "article title"
          type: "text"
