# Site settings
title: The Making of History
legal: All Rights Reserved
# email: enquiries@leeds-ebooks.co.uk
description: >
  History at its worst. # Pure, unfiltered history. # Untapped history. #
  History best not repeated. # History written by the victors, mocked by us.
baseurl: / # the subpath of your site, e.g. /blog/
url: http://www.makingofhistory.com # the base hostname & protocol for your site

authors: &AUTHORS
  - value: 'lee-bellamy'
    name: 'Lee Bellamy'
  - value: 'elliott-took'
    name: 'Elliott Took'

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      author:
        - lee-bellamy

exclude:
  - 'src'
  - 'liquid'
  - 'package.json'
  - 'node_modules'
  - 'webpack.config.js'

permalink: /article/:title/

# Assets
sass:
  style: compressed

prose:
  rooturl: ""
  siteurl: "http://leeds-ebooks.github.io/making-of-history"
  media: "images"
  ignore:
    - '_includes'
    - '_layouts'
    - '_sass'
    - 'css'
    - 'js'
    - 'liquid'
    - 'src'
    - 'timeline'
    - '_config.yml'
    - '.eslintrc.yml'
    - '.gitignore'
    - 'feed.xml'
    - 'index.html'
    - 'package.json'
    - 'webpack.config.js'
    - 'CNAME'
  metadata:
    '':
      - name: layout
        field:
          element: hidden
      - name: permalink
        field:
          element: hidden
      - name: weight
        field:
          element: hidden
      - name: show_in_menu
        field:
          element: hidden
    _posts:
      - name: published
        field:
          element: hidden
          value: true
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Article title
          type: text
      - name: featuredimage
        field:
          element: text
          label: Featured image URL
          help: Paste here the url from the body of the article, without "{{site.baseurl}}" e.g. "/images/lovely-picture.jpg"
          placeholder: url/to/the/image.jpg
          type: text
      - name: period
        field:
          element: text
          label: Year (4 digits required!) or range (separated by single hyphen, no spaces)
          help: e.g. 1735 or 1730-1736
          type: text
      - name: location
        field:
          element: text
          label: City or country
          type: text
      - name: author
        field:
          element: multiselect
          label: Author
          options: *AUTHORS
